sudo: required
services:
- docker
env:
  global:
  - DOCKER_HUB_USER=vbenji
script:
- docker-compose build
before_deploy:
- docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
deploy:
  provider: script
  script: docker-compose push
  on:
    branch: master
