sudo: required
services:
- docker
env:
  global:
  - DOCKER_HUB_USER=vbenji
  - secure: a0ZiRX3pr6T2/qKfGSqjQN0KiFJRnko9bHrf2sNRaRsFZqKY8cCPylc8UWWifNCFEKgk4W0+wkRi+vLS3nli545WyRLdbo4hQRNZnrKVLkNeUQNI2qAH1JMcNT4+NSykpHpptH22CWBEJtBs3cglHLQl0B0uBrLGaVW+NpZWoKVghn/3RmEfo/f+b+HrH3fmvNkY/+9naZLTZmYobVii4mFdpVmI6+Huf03AXFY5UKP7fGTvgKwmunlBrGX+xpK+DB5pAE1o44hNjtLqrLq7xRCasqBeuaX07066goNc3C7wx/Xa/f4P8+O9VBi71AK//qPABnV7yI1nue5CqKLYc/u16xaiGdBiZnmJmAdIeU9d/ne/Q/qyoGDWeOvisGbcVM1gyMzdZYEnU9WgVpreg6OoJshPANQXLmlKCKrIolzTQikm2bSFtdM2nZh/Dy2xvulbbqRNhLsaVyD73hXYmc/va7zbwzCLdaOXNKxwUClLj3mOk/pocTQLagzmmCtN/ixzACVLJQdBQuApJNMJickKrBCnDgAY5T+UtB+vGTiA4BwmWIqY9baEDacDNfdl+9ijKjWMyE5CCewvTFKyu5xtLfpcRIIxCr5/rOltyTPMqFoEkuDejLeWfDmA4FCD2YPs1QXlVN8STafXIBOoWqLdnhrqAU8wld32k0Ksw7c=
script:
- docker-compose build
before_deploy:
- docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
deploy:
  provider: script
  script: docker-compose push
  on:
    branch: master
